# Base image and maintainer information
FROM --platform=linux/amd64 ubuntu:23.10
LABEL maintainer="lastname@gmail.com" \
      version="0.2" \
      description="Surge XT 1.3.0 synthesizer through Python, dockerized on Ubuntu 23.10 for AMD64"

# Set environment variables
ENV LANG C.UTF-8
ENV TZ=Etc/UTC
ENV DEBIAN_FRONTEND=noninteractive
ENV HOME=/home/surge
ENV PATH="/home/surge/venv/bin:$PATH"

# Set working directory
WORKDIR /root/

# Set timezone and update system packages
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && \
    echo $TZ > /etc/timezone && \
    apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y \
    # Development tools
    git build-essential cmake \
    # Python and utilities
    python3-pip python3.11-venv \
    # X11 and GUI libraries
    libcairo2-dev libxkbcommon-x11-0 libxkbcommon-dev libxcb-cursor-dev \
    libxcb-keysyms1-dev libxcb-util-dev libxrandr-dev libgtk-3-dev \
    # Audio libraries
    libsndfile-dev libasound2-dev libjack-jackd2-dev \
    # Networking and protocol libraries
    libcurl4-openssl-dev libwebkit2gtk-4.0-dev \
    # Essential utilities
    vim rsync less bc wget \
    # Security and certificates
    apt-transport-https ca-certificates gnupg libssl-dev \
    # User management
    sudo

# Install updated CMake from Kitware
#RUN wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor -o /usr/share/keyrings/kitware-archive-keyring.gpg && \
#    echo 'deb [signed-by=/usr/share/keyrings/kitware-archive-keyring.gpg] https://apt.kitware.com/ubuntu/ jammy main' | tee /etc/apt/sources.list.d/kitware.list >/dev/null && \
#    apt-get update && \
#    apt-get install cmake -y

# Add non-root user 'surge' with passwordless sudo privileges
RUN useradd -ms /bin/bash surge && \
    echo "surge:surge" | chpasswd && \
    echo 'surge ALL=(ALL) NOPASSWD:ALL' > /etc/sudoers.d/surge && \
    chmod 0440 /etc/sudoers.d/surge

# Clone and build Surge Synthesizer as user 'surge'
USER surge
RUN cd /home/surge && \
    git clone --branch release_xt_1.3.0 --depth 1 https://github.com/surge-synthesizer/surge.git && \
    cd surge && \
    git submodule update --init --recursive


# Fix missing <cstdint> include in cpufeatures.cpp and cpufeatures.h
RUN sed -i '1i#include <cstdint>' /home/surge/surge/libs/sst/sst-plugininfra/src/cpufeatures.cpp && \
    sed -i '1i#include <cstdint>' /home/surge/surge/libs/sst/sst-plugininfra/include/sst/plugininfra/cpufeatures.h


USER root
RUN cd /home/surge/surge && \
    /usr/bin/cmake -Bbuildpy -DSURGE_BUILD_PYTHON_BINDINGS=True -DCMAKE_BUILD_TYPE=Release && \
    /usr/bin/cmake --build buildpy --target surgepy --config Release --target surge-staged-assets && \
    /usr/bin/cmake --install buildpy --config Release && \
    /usr/bin/cmake --build buildpy --config Release --target surge-staged-assets && \
    /usr/bin/cmake --install buildpy --config Release && \
    rm -rf .git
#    rm -rf /home/surge/surge/buildpy

USER surge

# Create and activate a virtual environment for Python
RUN python3 -m venv /home/surge/venv && \
    echo "source /home/surge/venv/bin/activate" >> /home/surge/.bashrc && \
    pip install --upgrade pip && \
    pip install tqdm ipython numpy soundfile python-slugify

# Copy example files
COPY example.py run.py /home/surge/

# Set ownership of home directory
USER root
RUN chown -R surge:surge /home/surge/
USER surge

# Clean up unnecessary packages and files
USER root
RUN apt-get remove -y libcairo2-dev libxkbcommon-x11-0 libxkbcommon-dev libxcb-cursor-dev libxcb-keysyms1-dev libxcb-util-dev && \
    apt-get autoclean && \
    apt-get autoremove -y && \
    rm -rf /var/lib/apt/lists/*

# Set the working directory to /home/surge
WORKDIR /home/surge
